### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by deedw** [barrysteyn/node-scrypt#100]
Thank you for your work on this great module

It would be really helpful if you were able to add a changelog file to the repo to assist with upgrade decisions.

**Comment by barrysteyn** [comment]
Hi @deedw 

Thanks for the feedback. Yeah, I get you. Let me try defend myself (although this is not a good defence) by stating that I also lead an engineering team and work a solid 10 hours a day (sometimes more). So I struggle with time.

Now for a favour: If you know the project, could you possibly create a changelog for me. I will correct it if need be, and I promise I will keep it up to date from now on?

**Comment by deedw** [comment]
I've used template from http://keepachangelog.com/ to populate a starter CHANGELOG for you.

https://gist.github.com/deedw/b3217f928ceaddd9aa41

**Comment by barrysteyn** [comment]
Excellent @deedw - Thank you. I will add it into my next build, and I will keep it up to date. Many thanks

**Comment by barrysteyn** [comment]
@deedw Just to show I am serious, I have updated this to 5.3, with the changelog as the reason for the update.
