### ISSUE TITLE
Build on MSVS 2015

### ISSUE THREAD

**Issue by Demurgos** [barrysteyn/node-scrypt#103]
Hi,
As mentioned in #88 , `node-gyp rebuild` fails when using Visual Studio 2015.
I know that node-gyp is intended to use with VS 2013 but more and more people will start using the new version of VS so it's better to track this issue and fix it.

It appears that the error is cause by the redefinition of `struct timespec` in `scrypt/win/include/gettimeofday.h`.

Here is the output for `node-gyp rebuild`
````bash
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.1.1 | win32 | x64
gyp info spawn python
gyp info spawn args [ 'C:\\Users\\Charles\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\projects\\node-scrypt\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Charles\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Charles\\.node-gyp\\4.1.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Charles\\.node-gyp\\4.1.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Charles\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\projects\\node-scrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\projects\\node-scrypt\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying scrypt/win/include/config.h to scrypt/scrypt-1.1.6/config.h
          1 file(s) copied.
  win_delay_load_hook.c
  Generating code
  Finished generating code
  copied_files.vcxproj -> D:\projects\node-scrypt\build\Release\\copied_files.node
  salt.c
  keyderivation.c
  pickparams.c
  hash.c
  win_delay_load_hook.c
  scrypt_wrapper.vcxproj -> D:\projects\node-scrypt\build\Release\\scrypt_wrapper.lib
  sha256.c
  crypto_scrypt-sse.c
  scryptenc_cpuperf.c
  memlimit.c
  mman.c
  gettimeofday.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\time.h(39): error C2011: 'timespec': 'struct' type redefinition (compiling source file ..\scrypt\scrypt-1.1.6\lib\scryptenc\scryptenc_cpuperf.c) [D:\projects\
node-scrypt\build\scrypt_lib.vcxproj]
  D:\projects\node-scrypt\scrypt\win\include\gettimeofday.h(9): note: see declaration of 'timespec' (compiling source file ..\scrypt\scrypt-1.1.6\lib\scryptenc\scryptenc_cpuperf.c)
  win_delay_load_hook.c
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Charles\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Charles\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\projects\node-scrypt
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
````
Commenting out the `struct` in `gettimeofday.h` seems to do the trick and allows to build scrypt. I'm not so good at C/C++ so I don't know how to properly fix it (in a non-hacky way) but here is the original definition of `struct timespec` as found in `C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\time.h`

````C
#pragma once
#define _INC_TIME

#include <corecrt.h>
#include <corecrt_wtime.h>

// [ ... ]

#ifndef _CRT_NO_TIME_T
    struct timespec
    {
        time_t tv_sec;  // Seconds - >= 0
        long   tv_nsec; // Nanoseconds - [0, 999999999]
    };
#endif

// [ ... ]
````

**Comment by barrysteyn** [comment]
Do the tests run okay? I remember when I made this functionality, as I don't have access to Windows, I used a machine with a VM. 

If the tests run okay, then I will add some functionality to ensure that scrypt will work on windows.

Also (although this will take some time), I am slowly updating this module to use scrypt 1.2.0 and I will aim for much better windows support.

**Comment by Demurgos** [comment]
I got 73 tests passing. (all of them)

It looks like an issue with the build step only. The system `timespec` is almost the same as the one in `gettimeofday.h`.
(`<time.h>` is at least included in `cpuperf.h`)

**Comment by barrysteyn** [comment]
Okay, this is very helpful. I will make a fix sometime this week. Would you mind checking it?

**Comment by Demurgos** [comment]
Sure ;)

**Comment by barrysteyn** [comment]
Hi @Demurgos 

Can I ask you try build the project at branch V5.3 - it should work for you out of the box. But the acid test is to get someone else with MS 2015 to also build it. If it works for them, then we can publish this.

**Comment by barrysteyn** [comment]
@Demurgos Ping! Did it work?

**Comment by Demurgos** [comment]
Hi
I just pulled `V5.3` and it worked fine. All tests passed.
This week-end I'll have access to an other computer with VS 2015 but it has a similar setup as the one I'm currently working with so I'm not sure if it will really help.
Did you try with VS 2013 with your Virtual Machine ?

**Comment by barrysteyn** [comment]
To tell you the truth, I don't have that VM anymore. But if it worked for you, then it should work on VS2013. What I am doing is using a macro expression to test if the version is less than VS 2015. If it is, then I define `timespec`, if not (as in your case), I leave it undefined.

Do you have VS 2013 and are you able to test it for me? If not, then I am going to release it. I am sure I will get plenty of feedback from people saying it does not work.

Can you please reply to this and tell me if you are able to test or not on 2013.

**Comment by Demurgos** [comment]
Sorry, I no longer have VS2013.
I got a student license for VS2015 recently so I uninstalled VS2013.
If you want, I could reinstall it but it would be in 3-4 days.

**Comment by barrysteyn** [comment]
Thanks, but that is not necessary. I am going to release this to the public, let's see what happens...

**Comment by barrysteyn** [comment]
Okay, with the release of 5.2.0, this issue should be solved.

**Comment by barrysteyn** [comment]
@Demurgos : Please can you do me a favour and clone v6, npm install, and then npm test and tell me if things are good.

Version 6 is going to seriously help fix things like you guys have experienced.

**Comment by Demurgos** [comment]
Hi,
I just checked out `v6`. `npm install` and `npm test` both work fine.

Good job.

**Comment by barrysteyn** [comment]
Excellent. This is really awesome: There is no need for this version to install OpenSSL for windows. So it should help windows users in a big way.
