### ISSUE TITLE
Documentation needs updating

### ISSUE THREAD

**Issue by IrishAdo** [barrysteyn/node-scrypt#107]
OK so I've upgrade to the latest and greatest version and was changing my code everything went well until I tried to verify the user account.

So I store the kdf hash as hex converting with .toString('hex') as per the instructions and I store that in by db.  I could not understand why the verify code would not work until I console logged some values out.

Example of code for verifying a password that has been hashed  then converted to hex and the hex stored in a database.

var scrypt = require("scrypt");

// this is a string where every two bytes represents one character
var hashedPassword  = '736372797074000e0000000800000001ffe170c44f07772d4d5e55df8c0a3d0ac85ce477b0f49216475149dcc2f4167466afce87633b5afff91cd7fb3996b79f54dc2f7a337183e08202ce1053b1288724f444e9712a1f13dc7dd0afba5bb8d8';

// decode the encode hex string
var kdfResult = new Buffer(hashedPassword,'hex');

//Synchronous
scrypt.verifyKdfSync(kdfResult, "password"); // returns true
scrypt.verifyKdfSync(kdfResult, "incorrect password"); // returns false

//Asynchronous
scrypt.verifyKdf(kdfResult, new Buffer("password"), function(err, result) {
  //result will be true
});

**Comment by barrysteyn** [comment]
Hi. What do you mean "I could not understand why the verify would not work"? Please can you give an example of how you thought it should work.

**Comment by IrishAdo** [comment]
Because I had converted the hash to hex. So I ended up with a string that represented a hex version of the hash. The I was asking the verifying function to verify the encoded string and not the decoded string.   ie "ado" is encoded to hex as "656879". I needed to convert it back to the unencoded string "ado". 

I converted that in my head so it might be wrong:-)

**Comment by barrysteyn** [comment]
I understand where you are coming from. I think that perhaps a general section on how to work with Buffers is needed (infact, I always get the same question). But the examples given in the README are accurate and correct.

**Comment by IrishAdo** [comment]
I don't disagree with you the examples are correct but in a live environment you would hash the password and store it somewhere first. Then on a different script you would compare that stored value. 

You could put a comment that the kfdresult is a buffer so if you convert it to a normal string for storage you will need to convert it back to a buffer

Either way thought I would raise the issue as a Google search might find the answer for someone

Ado
