### ISSUE TITLE
scrypt params question

### ISSUE THREAD

**Issue by vwal** [barrysteyn/node-scrypt#109]
Could you briefly and simply explain (or point to an explanation of) the scrypt params object, e.g.

`{'N':1048576,'r':8,'p':1}`

The `paramsSync` method creates this object, but since it is often also given directly in the examples, and since the example values seem to be difficult to derive from the values given to `params` or `paramsSync`, I'd like to know what the values signify directly. Perhaps they were explained in the linked whitepaper, but not being a cryptologist it didn't really open up to me. :-) Thanks for your help!

**Comment by simontabor** [comment]
@vwal This StackOverflow question might help https://stackoverflow.com/questions/11126315/what-are-optimal-scrypt-work-factors :)

**Comment by vwal** [comment]
@simontabor Oh, that's perfect!! Thank you for pointing that out; I didn't think of searching SO for it! 

@barrysteyn Maybe add this link to node-scrypt docs? :-)
