### ISSUE TITLE
Explain the resulting string length

### ISSUE THREAD

**Issue by gajus** [barrysteyn/node-scrypt#112]
It is not clear how to store the resulting base64 string in the database, i.e. what should be the size of the column.

```js
import scrypt from 'scrypt';

scrypt
    .params(0.2)
    .then((scryptParameters) => {
        return scrypt.kdf('test', scryptParameters);
    })
    .then((result) => {
        console.log( result.toString('base64').length === 128 );

        return scrypt.verifyKdf( new Buffer(result.toString('base64'), 'base64') , 'test');
    })
    .then((result) => {
        console.log({result});
    });
```

All my tests seem to show that regardless of the input the resulting hash length is 128 characters. Though, I am sure this is variable (otherwise it would have been documented as such).

What exactly determines the length of the hash and how to calculate it?

**Comment by Demurgos** [comment]
In the readme, there is a link under the kdf section to [this explanation of the HMAC format](http://security.stackexchange.com/questions/88678/why-does-node-js-scrypt-function-use-hmac-this-way/91050#91050).

 > 
  When encrypting something using the scrypt key derivation function, a 96 byte result is produced

96 bytes encoded in base64 are effectively 128 chars so this is not variable.

**Comment by gajus** [comment]
Thank you. Missed it. Was searching for "128" keyword.
