### ISSUE TITLE
scrypt function to store passwords:

### ISSUE THREAD

**Issue by ngoctranfire** [barrysteyn/node-scrypt#114]
According to a post I read:
```
If your interested in this module is to produce hashes to store passwords, then I strongly encourage you to use the hash function. The key derivation function does not produce any message authentication code to ensure integrity. You will also have to store the scrypt parameters separately. Lastly, there is no native verify function included in this module.
```

However, I'm confused because I read the documentation and I noticed there is a scrypt.hash() function and a scrypt.kdf and a scrypt.verifykdf function....

Should I be using scrypt.kdf to store my password or should I use scrypt.verifykdf?

I am currently using scrypt.hash(password, params, salt)...
If i want to verify a password, should I just compute the hash using scrypt.hash() and then comparing that the two are the same?

Or should I use scrypt.kdf() and then use scrypt.verifyKdf() to verify the two are the same...?

Sorry this is not really an issue. This is more of a question.

**Comment by DiknT** [comment]
with latest version >= 5 you want to save the result of script.kdf as the users hashed password (documentation says scrypt.kdf internally uses the scrypt.hash itself). Then with script.verifyKdf(savedPW, inputPW) you check validity of password entered at login attempt.

**Comment by ngoctranfire** [comment]
@DiknT What about the salt? The scrypt.kdf doesn't actually take in a salt? Should I just append the salt to my password manually?

**Comment by DiknT** [comment]
the kdf function takes care of salting, no need to add it yourself: KDF: This should be used for hashing and checking passwords as it incorporates salt as well as HMAC into its format.

**Comment by ngoctranfire** [comment]
@DiknT How does the verifykdf actually verify the password again if the salt is randomly generated...? This doesn't really make sense to me at all...

**Comment by barrysteyn** [comment]
Salt is random but is never encrypted. So it's stored in the clear and
anyone can read it. Remember what salt is achieving: It's thwarting a
rainbow attack. So we just want to make identical passwords look different
when hashed, and that's all the salt is doing.

**Comment by ngoctranfire** [comment]
Nevermind. I just read the c function and realized that the salt is the characters 16-32. We take it from there

**Comment by DiknT** [comment]
check the links mentioned in section for KDF, the salt is saved in the bytes 16-46 of the resulting kdf. From the documentation:

To explain why HMAC is used, lets have a quick recap. When encrypting something using the scrypt key derivation function, a 96 byte result is produced with the following break down:

 bytes 0-5: The word "scrypt"
 byte 6: 0
 byte 7: logN
 bytes 8-11: r
 bytes 12-15: p
 bytes 16-47: salt (which is 32 bytes)
 bytes 48-63: A 16 byte SHA256 checksum (hash) of the contents of bytes 0 to 47
 bytes 64-95: A 32 byte HMAC hash of bytes 0 to 63 with the key being the scrypt cryptographic hash

**Comment by ngoctranfire** [comment]
@DiknT Thanks a lot! Makes a lot of sense now!
