### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by BrandonZacharie** [barrysteyn/node-scrypt#116]
I get the following when attempting to run tests.

```
➜  scrypt git:(develop) ✗ npm test

> scrypt@6.0.1 test /Users/Brandon/.../node_modules/scrypt
> mocha tests/scrypt-tests.js

module.js:328
    throw err;
    ^

Error: Cannot find module './options'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Brandon/.../node_modules/.bin/mocha:11:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
npm ERR! Test failed.  See above for more details.
```

**Comment by barrysteyn** [comment]
This seems like a setup problem with mocha. I can't say why this is not working, but I don't think it is due to my code. Can you try again?

**Comment by BrandonZacharie** [comment]
The entry for `npm test` (`mocha tests/scrypt-tests.js`) references `mocha` without a path. I tried running the tests again but with a relative path to `mocha` and the `tests` directory and it worked. I recommend changing the entry for `npm test` to `node_modules/mocha/bin/mocha tests` to ensure it uses the module's version of mocha. I also recommend changing the file path to just the `tests` directory so that it runs all test scripts (although there is only one script in the directory at the moment, you may want to split them up and/or add more in the future).
![screen shot 2016-02-17 at 13 02 41](https://cloud.githubusercontent.com/assets/27306/13124755/c78d59c8-d576-11e5-8604-8a83bd372190.png)

**Comment by barrysteyn** [comment]
An absolute path is not necessary for npm to find packages. What version of npm are you using?

**Comment by BrandonZacharie** [comment]
`mocha` is a binary; I don't think `mocha tests` works unless it's installed globally (and thus in `$PATH`). I am using `npm@2.14.18`
