### ISSUE TITLE
?Documentation is out of sync?

### ISSUE THREAD

**Issue by JonathanHayward** [barrysteyn/node-scrypt#117]
https://github.com/barrysteyn/node-scrypt says nearby:

> kdf
> 
> Note: In previous versions, this was called hash.

Then it goes on to say:

> hash
> 
> Note: In previous versions, this was called kdf.

Which is intended? Does the following code encrypt a password:

> var encrypted_key = scrypt.hash(key, scrypt.params(.1));

--or--

> scrypt.hash(key, scrypt.params(.1), function(err, obj) {
>  if (!err) {
>    /* Save obj as an encrypted string */
>  }
>});

**Comment by DiknT** [comment]
Both are intended, names changed with version 5. As it states on top:

Migrating To Version 5
Version 5 is not backward compatible, but it should still be easy to migrate. Please read the api section to see what's changed. One big change that is worth noting is a name change: What used to be called hash has now been changed to kdf and conversely, what was kdf is now called hash.

Now, kdf is used to encrypt the password (including automated salting). kdf function internally uses the hash function.
