### ISSUE TITLE
Decryption

### ISSUE THREAD

**Issue by somebody1234** [barrysteyn/node-scrypt#129]
How would I decrypt a scrypt-generated hash?

**Comment by BrandonZacharie** [comment]
You cannot decrypt a hash. Encryption and decryption are opposites, while hashing has no opposite function.

If you'd like to know how to use scrypt to verify a scrypt-generated hash, please see the [`verifyKdf` section of the readme](https://github.com/barrysteyn/node-scrypt#verifykdf-1). If you're looking for information on how to crack ("decrypt") a scrypt-generated hash, this isn't the place.
