### ISSUE TITLE
Windows Visual Studio 2015 installing issue

### ISSUE THREAD

**Issue by ozanyurt** [barrysteyn/node-scrypt#138]
> ~ $ npm install scrypt
> 
> scrypt@6.0.3 preinstall C:\Users\Ozan\node_modules.staging\scrypt-95637f5c
> node node-scrypt-preinstall.js
> 
> scrypt@6.0.3 install C:\Users\Ozan\node_modules\scrypt
> node-gyp rebuild
> 
> C:\Users\Ozan\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\Ozan\AppData\Roaming\nvm\v6.7.0\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Warning: Missing input files:
> C:\Users\Ozan\node_modules\scrypt\build..\scrypt\win\include\config.h
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   Copying scrypt/win/include/config.h to scrypt/scrypt-1.2.0/config.h
>   The system cannot find the file specified.
>   win_delay_load_hook.c
> C:\Users\Ozan\AppData\Roaming\nvm\v6.7.0\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__ pfnDliNotifyHook2': redefinition; different type modifiers [C:\Users\Ozan\node_modules\scrypt\build\copied_files.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '**pfnDliNotifyHook2
>   '
>   memlimit.c
>   keyderivation.c
>   pickparams.c
>   hash.c
>   win_delay_load_hook.c
> C:\Users\Ozan\AppData\Roaming\nvm\v6.7.0\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '** pfnDliNotifyHook2': redefinition; different type modifiers [C:\Users\Ozan\node_modules\scrypt\build\scrypt_wrapper.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2
>   '
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\Ozan\AppData\Roaming\nvm\v6.7.0\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Windows_NT 10.0.14936
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Ozan\AppData\Roaming\nvm\v6.7.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Ozan\node_modules\scrypt
> gyp ERR! node -v v6.7.0
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Ozan\package.json'
> npm WARN Ozan No description
> npm WARN Ozan No repository field.
> npm WARN Ozan No README data
> npm WARN Ozan No license field.
> npm ERR! Windows_NT 10.0.14936
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "scrypt"
> npm ERR! node v6.7.0
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the scrypt package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs scrypt
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls scrypt
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:

If I rename __pfnDliNotifyHook2 with something else, it can be successfully build.

> node-gyp\src\win_delay_load_hook.c(34): error C2373: '__ pfnDliNotifyHook2': redefinition; different type modifiers [C:\Users\Ozan\node_modules\scrypt\build\copied_files.vcxproj]

`PfnDliHook __pfnDliNotifyHook2_newname = load_exe_hook;`

node v6.7.0
npm v3.10.3

**Comment by justinmchase** [comment]
This is fixed with node>=7.0.0

**Comment by worldspawn** [comment]
I updatedto node 7.4.0 and am having the same problem. Reinstalled build tools and node-gyp etc.
npm 3.9.3

```npm install --save scrypt

> scrypt@6.0.3 preinstall C:\Users\critc\Source\arch\src\api\node_modules\.staging\scrypt-11164450
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install C:\Users\critc\Source\arch\src\api\node_modules\scrypt
> node-gyp rebuild


C:\Users\critc\Source\arch\src\api\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\critc\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\critc\Source\arch\src\api\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying scrypt/win/include/config.h to scrypt/scrypt-1.2.0/config.h
  The system cannot find the file specified.
  win_delay_load_hook.c
C:\Users\critc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: ' __pfnDliNotifyHook2': redefinition; different type modifiers [C:\Users\critc\Source\arch\src\api\node_modules\scrypt\bu ild\copied_files.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
  ifyHook2'
  memlimit.c
  keyderivation.c
  pickparams.c
  hash.c
  win_delay_load_hook.c
C:\Users\critc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: ' __pfnDliNotifyHook2': redefinition; different type modifiers [C:\Users\critc\Source\arch\src\api\node_modules\scrypt\bu ild\scrypt_wrapper.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
  ifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\critc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\critc\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\critc\Source\arch\src\api\node_modules\scrypt
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
npm WARN api@0.0.0 No description
npm WARN api@0.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\critc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "scrypt"
npm ERR! node v7.4.0
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\critc\Source\arch\src\api\npm-debug.log```

**Comment by fanatid** [comment]
@worldspawn try install latest npm before install node-scrypt `npm -g install npm@next`

**Comment by worldspawn** [comment]
thanks i got it working. not sure how exactly but there was a lot of uninstalling/reinstalling.
