### ISSUE TITLE
SSE2 version is not being build?

### ISSUE THREAD

**Issue by dchest** [barrysteyn/node-scrypt#149]
When I install the module, it doesn't seem to use SSE2 version, which is almost twice as fast on supporting CPUs. When I manually added `scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix_sse2.c` to https://github.com/barrysteyn/node-scrypt/blob/master/binding.gyp#L57-L58 and tweaked code a bit, it works.

**Comment by barrysteyn** [comment]
This is awesome. Did you verify the speed increase?

**Comment by dchest** [comment]
Sure, here are results on my MacBook Pro with `r=8, p=1` and the given log(N):

```
logN    No SSE2       SSE2
-----  ---------    --------
18       939 ms       688 ms
19      1749 ms      1318 ms
20      3763 ms      2624 ms
```

**Comment by barrysteyn** [comment]
Okay, very cool. Now I need to look at the code (I have not been as diligent as I should have been), but will this change break things for CPU's that do not support SSE2?

**Comment by dchest** [comment]
I'm not good with the build systems, but the original scrypt build configuration detects when the compiler supports SSE2 and if so, builds both versions. Then, at runtime, it detects if the CPU supports SSE2 (using `libcperciva/cpusupport/cpusupport_x86_sse2.c`, here https://github.com/barrysteyn/node-scrypt/blob/master/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt.c#L209-L219) and calls `crypto_scrypt_smix_sse2` if it does, or `crypto_scrypt_smix` if it doesn't dynamically.

I guess your build system needs: 

* add `scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix_sse2.c` to `binding.gyp`.
* during node-gyp configure detect if there's SSE2 support in the compiler. If so, define `CPUSUPPORT_X86_SSE2` (not sure how it's done) and pass sse2 flags to compiler.

Searching this repo for SSE shows that you worked on some SSE detection, but it's no longer here?

**Comment by barrysteyn** [comment]
Yes, you are correct. But I remember there being a problem with SSE2 detection. If I may ask: What do you use the library for. I love hearing about what people use it for.

**Comment by dchest** [comment]
I think previous versions of scrypt didn't include runtime SSE2 detection, which is probably why people had problems with it.

As for the library, currently I'm using it for benchmarking the native performance to compare with pure JS https://github.com/dchest/scrypt-async-js

**Comment by barrysteyn** [comment]
I would be really interested in the results. Please can you post them up here.

**Comment by dchest** [comment]
On the same laptop with the same parameters as the above posted:

```
logN       Chrome       Firefox
----     --------     ---------
18        1524 ms     4306 ms
19        2970 ms     8802 ms
20        5930 ms    17227 ms
```

So, less than half speed of SSE2 version on Chrome. Not bad :)

**Comment by barrysteyn** [comment]
BTW: You are very welcome to submit a PR to fix the problem. I will get down to it eventually, but it may take some time.

**Comment by dchest** [comment]
Unfortunately, I'm not familiar with `gyp`, so for myself I just commented-out some stuff, and passed some environmental variables, and did something else (I already forgot what), so it kinda works on my machine, but definitely isn't ready for mass consumption :)

**Comment by barrysteyn** [comment]
see #150
