### ISSUE TITLE
If installed on macOS, cannot deploy to AWS Lambda

### ISSUE THREAD

**Issue by rhlsthrm** [barrysteyn/node-scrypt#158]
I am developing an API that uses web3, which depends on scrypt. I am using the Serverless Framework, which deploys code into AWS Lambda functions. The package gets zipped up from my hard disk and pushed to the Lambda infrastructure directly. I am getting the following error at the start of my stack trace:

`/var/task/node_modules/scrypt/build/Release/scrypt.node: invalid ELF header`

I Googled around and I believe this is caused by the library being installed on my Mac system, which is incompatible with the Unix-based Lambda environment. Is this true? If so, is there a workaround or possible fix for this?

**Comment by davehermann** [comment]
I don't use Serverless, and can't comment on its specifics or how it may automate NPM, but I do use this module on AWS Lambda.  AWS Lambda requires that native modules be compiled on its execution environment.  See https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html for specifics.

You'll have to launch the AMI listed, and install the module to get gyp to compile node-scrypt correctly.  The resulting `node_modules` directory can then be used to deploy to AWS Lambda.

Depending on how Serverless operates, you may have to have your function and all dependencies built on that AMI, or even use Serverless to deploy from there.

**Comment by rhlsthrm** [comment]
@davehermann you are correct and that is indeed the workaround. If this is as designed, we can close the issue.

**Comment by BrandonZacharie** [comment]
I agree with @davehermann and I use neither AWS Lamda nor Serverless but I know that
scrypt must be built on or for the target machine.
