### ISSUE TITLE
node-gyp builds to Release/scrypt.node

### ISSUE THREAD

**Issue by ryanio** [barrysteyn/node-scrypt#169]
Hey, thanks for the great library.

I'm running it on Mac OS X 10.13.2 with node v9.2.1 and I'm getting the error:

```
 Cannot find module './build/Release/scrypt' from 'index.js'
```

It looks like node-gyp is building to Release/scrypt.node:

```
...
SOLINK_MODULE(target) Release/scrypt.node
gyp info ok
```

But index.js looks for: `require("./build/Release/scrypt")`

Related to #162, but if I just rename to `require("./build/Release/scrypt.node")` I get the error:

```
Module parse failed: node_modules/scrypt/build/Release/scrypt.node Unexpected character '�' (1:0)
[1] You may need an appropriate loader to handle this file type.
```

Would love any tips or clues into what to try next.

**Comment by ryanio** [comment]
I believe using [node-loader](https://github.com/webpack-contrib/node-loader) along with @fanatid's PR #144 fixed this for me :)

**Comment by joey-he8x** [comment]
Why close the issue while the problem is still not fixed, I want to use it in node env, node-loader not helping.

**Comment by hammadzz** [comment]
This doesn't work with `ts-node` either!
