### ISSUE TITLE
Hashing, Storing, Retrieving, and Verifying Password Hash (Getting Unhelpful Blank Error Message or "Error")

### ISSUE THREAD

**Issue by blackwire** [barrysteyn/node-scrypt#181]
So~ I'm trying to use this on a web server to hash passwords and store base64 encoded in the database then pull them back out and verify the provided password against the hash. Seems simple enough, but when I try this I get an error being returned from verifyKdf that is just logs "Error" when I console log the error, error.message is blank when logged, and error.stack is "Error" when logged. I have no idea what I'm doing wrong, but here is a sample of the code:

```
scrypt.verifyKdf(result[0].password, password, function(error)
{
    if (error)
    { console.log(error); }
}
```

result[0].password when logged to the console definitely shows up as a buffer. I also tried to call Buffer.from(result[0].password, 'base64') and use this, but that resulted in the same behavior.

Initially I'm storing the hash like this:
```
scrypt.params(1.00, function(error, params)
{
    if (error)
    { console.log(error); return; }

     scrypt.kdf(password, params, function(error, passwordHash)
     { 
         // database call here to store password hash
     }
}
```

I tried to understand the documentation and lookup other examples... I think I'm doing this right, but I could be way off the mark. Any help would be appreciated.

**Comment by chrisveness** [comment]
I think Barry may have abandoned this project. If you are using Node.js v10.5.0+, you could try my [scrypt-kdf](https://www.npmjs.com/package/scrypt-kdf), which is a simple pure-JS wrapper around the native OpenSSL implementation of scrypt. If you try it, I would be interested to know whether you have any issues.

**Comment by blackwire** [comment]
@chrisveness, thanks! I think I ended up going a different route all together. I appreciate the link. I'll take a look at this as well. If I do end up using scrypt-kdf I'll definitely let you know if I run into anything.
