### ISSUE TITLE
Does not build on raspberry pi

### ISSUE THREAD

**Issue by fiws** [barrysteyn/node-scrypt#44]
Hi,

I get the following error trying to install scrypt on my raspberry pi:
```shell
scrypt ➤ npm install scrypt                                                                                                                                                                
npm http GET https://registry.npmjs.org/scrypt
npm http 304 https://registry.npmjs.org/scrypt

> scrypt@3.0.1 install /home/fiws/scrypt/node_modules/scrypt
> node-gyp rebuild

make: Entering directory '/home/fiws/scrypt/node_modules/scrypt/build'
  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  AR(target) Release/obj.target/scrypt_wrapper.a
  COPY Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
../scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.c:34:23: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
                       ^
compilation terminated.
scrypt_lib.target.mk:95: recipe for target 'Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o' failed
make: *** [Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o] Error 1
make: Leaving directory '/home/fiws/scrypt/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.10.37-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fiws/scrypt/node_modules/scrypt
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! scrypt@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@3.0.1 install script.
npm ERR! This is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.10.37-1-ARCH
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "scrypt"
npm ERR! cwd /home/fiws/scrypt
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/fiws/scrypt/npm-debug.log
npm ERR! not ok code 0

```

This *might* be because of some missing packages (It is a fresh install of Arch), but I can't figure out which ones are missing.

**Comment by kermit666** [comment]
I just tried master and it didn't not fix this issue for me - still complaining about a missing `emmintrin.h`. Say if you need any more testing - I'd love to see this issue fixed.

**Comment by barrysteyn** [comment]
Hi All
I will look into this over the weekend. Sorry for the delay. Just to note that I am going to be releasing a new version of scrypt within the next three to four months which is a not a C++ addon - it uses pure JavaScript/Node - this should solve everyone's problems.

**Comment by barrysteyn** [comment]
@kermit666 I may call on your help to test things.

**Comment by kermit666** [comment]
@barrysteyn :+1: I have a CuBox-i running constantly at home for developing @cloudfleet stuff, so no problem.

**Comment by fiws** [comment]
like https://github.com/tonyg/js-scrypt
wouldn't this be a lot slower than the C++ addon implementation? I imagine scrypt being very cpu intensive. (I might be wrong?)

**Comment by barrysteyn** [comment]
@fiws or anyone actually, I would like some help solving this issue. If you are prepared to work with me, then lets do it. I am releasing a Nan updated version of this library, after which, I want to nail this bug. The nan update has been completed, I am just waiting for the community to give feedback, so we can do this now

**Comment by barrysteyn** [comment]
@fiws Also, I should comment on that link. I think the author has used a C++ to JavaScript compiler to make pure JS out of the code. That is not the approach I am going to take. I wish to make my library from the ground up by hand. Of course, since this library is so popular, I am also going to support it and keep developing on it.

**Comment by fiws** [comment]
@barrysteyn would love to still help, but I can't find the SD card for my raspberry right now.

**Comment by barrysteyn** [comment]
@flws I think I have solved this problem now - I no longer use CPUID. I am going to close this issue, but I expect it to build properly on raspberry pi now. If you have an issue down the road, then reopen the issue.
