### ISSUE TITLE
node-scrypt performs unused work

### ISSUE THREAD

**Issue by oconnore** [barrysteyn/node-scrypt#45]
```C
int
Hash(const uint8_t* passwd, size_t passwdSize,
     uint8_t* hash, uint32_t logN, uint32_t r, uint32_t p) {
// ...
    uint8_t dk[64],
// ------------^
        salt[32],
        hbuf[32];
    uint8_t * key_hmac = &dk[32];
// --------------------------^
    if (ScryptKeyDerivationFunction(passwd, passwdSize,
        salt, 32, N, r, p, dk, 64))
// ----------------------------^
        return (3);

```

https://github.com/barrysteyn/node-scrypt/blob/master/src/scryptwrapper/hash.c#L46
https://github.com/barrysteyn/node-scrypt/blob/master/src/scryptwrapper/hash.c#L57

There is no need to derive a key twice as long as is consumed by the "`Hash`" function. Setting the `key_hmac` offset to 0, and changing the `dkLen` to 32 resolves this.

**Comment by barrysteyn** [comment]
Have you actually tried to change the code and see what happens when you do this.
