### ISSUE TITLE
Extracting different sizes of N from hash?

### ISSUE THREAD

**Issue by shekov** [barrysteyn/node-scrypt#51]
Looking at the hash format:

bytes 6-15: Scrypt parameters N, r, and p

But these variables can be different sizes, especially N, since it can have a really big size (1048576), or a really small one (2)? The big one takes up more bits then the small one.

So how then do you extract these N, r and p values when doing 'verify', is there a delimiter between these 3 values?

**Comment by barrysteyn** [comment]
RTFM!!! :)
