### ISSUE TITLE
#error "SSE2 instruction set not enabled" in Virtualbox

### ISSUE THREAD

**Issue by rogusdev** [barrysteyn/node-scrypt#53]
As others have reported, but for different reasons, I cannot npm install scrypt -- I get this error:
In file included from ../scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.c:34:0:
/usr/lib/gcc/i686-linux-gnu/4.8/include/emmintrin.h:31:3: error: #error "SSE2 instruction set not enabled"

I am fairly confident that this problem is related to the fact that I do my development in a Virtualbox instance.  Virtualbox does not support SSE in its VMs: https://www.virtualbox.org/ticket/8651 .  They have experimental support: https://www.virtualbox.org/manual/ch09.html#sse412passthrough .  However, I tried the experimental flags and it did not seem to fix the situation here.

If it is possible for your "detect SSE" branch you have mentioned on another bug card to get merged into trunk, that would be great.  If it still needs testing, I am confident I can reproduce this issue for you.  (I am able to build/install successfully on my laptop, just not in my vbox instance.)

To add some weight to the consideration, Vagrant is growing in popularity for dev/testing environments, and that runs (by default / for most) on Virtualbox.

I would very much like to be able to use this library, it looks great!

**Comment by barrysteyn** [comment]
Hi - I am sorry I am replying so late to this. If you are still available, I think I may have a fix. Give me a shout here.

**Comment by barrysteyn** [comment]
This should be fixed in the new release.
