### ISSUE TITLE
Segfault in master

### ISSUE THREAD

**Issue by dpatti** [barrysteyn/node-scrypt#61]
Previous discussion: https://github.com/barrysteyn/node-scrypt/issues/39#issuecomment-76826204

It looks like the change you made to add the hidden `_hashEncoding` was lost when the nan branch got merged to master, and I'm seeing the segfault again.

**Comment by barrysteyn** [comment]
Whoops, sorry. This is fixed and already resubmitted to NPM again. Please can you test and confirm for me?

**Comment by dpatti** [comment]
@barrysteyn Looks good, thanks for the fast turnaround :+1:
