### ISSUE TITLE
4.x version needs AVX instruction set?

### ISSUE THREAD

**Issue by erlichmen** [barrysteyn/node-scrypt#62]
I just update to the latest version of scrypt (4.x.x) which changed the way the SSE is detected.
The application that use this module crashes when running on Google Cloud Platform with "Illegal Instruction" exception.  

Here is the instructions bytes that crashes the app (I used valgrind to find them):  0xC5 0xF9 0x57 0xC0 0xE8 0x6B 0xE1 0xFF

Using disassembly those instructions are:
c5f957c0	vxorpd xmm0,xmm0,xmm0
e8	       .byte 0xe8
6be1ff	imul   esp,ecx,0xffffffff

vxorpd is an AVX instruction which indeed isn't supported by the CPU.
I have no idea where in the code such instruction is needed or how to proceed from here.
Maybe one of the intrinsics in crypto_scrypt-sse.c got translated into the above code?

**Comment by barrysteyn** [comment]
Hi @erlichmen 

This is very interesting. To my knowledge, no AVX instruction is being used explicitly. However,  I am setting a gcc flag (-march=native) that may for some reason result in the compiler introducing those instructions. Okay, I need some more information from you:

 1. Can you determine what architecture (i.e. type of cpu) your Google Cloud Compute instance is running on (e.g. x64, ia32, arm etc)
 2. What version of Node or IO is being used?
 3. If I prepare a special branch for you, are you able to deploy that to Google Cloud to test?

Thanks, I am sure we can solve this together.

**Comment by erlichmen** [comment]
1. The architecture is definitely x64 and most SSE operations are supported but no AVX, here is a dump of /proc/cpuinfo:  
  processor	: 0  
  vendor_id	: GenuineIntel  
  cpu family	: 6  
  model		: 45  
  model name	: Intel(R) Xeon(R) CPU @ 2.60GHz  
  stepping	: 7  
  microcode	: 0x1  
  cpu MHz		: 2600.000  
  cache size	: 20480 KB  
  physical id	: 0  
  siblings	: 2  
  core id		: 0  
  cpu cores	: 2  
  apicid		: 0  
  initial apicid	: 0  
  fpu		: yes  
  fpu_exception	: yes  
  cpuid level	: 13  
  wp		: yes  
  flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc nopl xtopology pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes hypervisor lahf_lm
  bogomips	: 5200.00  
  clflush size	: 64  
  cache_alignment	: 64  
  address sizes	: 46 bits physical, 48 bits virtual  
  power management:  
 2. I'm running v0.10.36
 3. sure

A few observations:
 1. What if I compile on arch that has AVX (or SSE for that matter) but the target doesn't? for example compiling inside a docker container (my case) and deploying onto a different host. Some sort of dynamic dispatching is needed in that case I was under the impression that using intestrics suppose todo that but obviously I'm wrong.
 2. Some Google Cloud instances do have AVX instructions set

**Comment by barrysteyn** [comment]
Hi @erlichmen 

You have a good point regarding point 1, which is why I think things are happening to you. Just researched a bit about `march=native` and yup, this is the very case that they warn about (compiling on a machine that is not the target).

Let me change the flags and see if it works. Are you able to test if I give you a branch?

**Comment by erlichmen** [comment]
@barrysteyn Sure, give me the branch and I'll test

**Comment by barrysteyn** [comment]
@erlichmen Okay, I have created a branch called Shay. It does not have the offending switch. Can you test it out and report back here.

**Comment by barrysteyn** [comment]
@erlichmen Yikes, wait two seconds, I forgot to submit the file

**Comment by barrysteyn** [comment]
@erlichmen Okay, can you try now (correct files are submitted and pushed)

**Comment by erlichmen** [comment]
I tested with the latest files on the same platform and it seems to be **working**

**Comment by barrysteyn** [comment]
@erlichmen I thought so. Thanks so much for the feedback. I will adjust and republish on NPM (within the next 15 minutes).

**Comment by barrysteyn** [comment]
This issue is resolved in 3332f85c9fee5f11d352e83102a538b139d2a715
