### ISSUE TITLE
Make sure to push tags

### ISSUE THREAD

**Issue by mike-marcacci** [barrysteyn/node-scrypt#64]
Hey @barrysteyn! Thanks again for the awesome project. Just a quick reminder to push any version tags you've got locally. I was just looking for a diff between two versions (just to satisfy a curiosity of mine) and noticed that the tags are missing from the repo.

Cheers!

**Comment by barrysteyn** [comment]
@mike-marcacci Unfortunately, when I started this project, I also started learning git. I knew about tagging when I was using SVN, but the information overload resulted in me not tagging releases. This is a mistake (I know) but I just don't have time to waddle through the history and start tagging now.

I would consider it a great addition and help to this project if you would go into the past and start tagging for me. In that case, I will then religiously tag all my future releases.

**Comment by mike-marcacci** [comment]
Oh ya, I wouldn't mind doing that at all! I just mentioned this here because if you use the npm cli to do something like `npm version minor` or `npm version v2.1.0` etc. it automatically creates the tags for you. I frequently run `npm version patch && npm publish` and totally forget to push the created tag to my repo. Thought that might be the case here. I'm not sure it's possible to pull-request a tag, but if it is I'll find time to reconstruct the tags!

**Comment by tellnes** [comment]
My publish line is:
```bash
npm version (major|minor|patch) && npm publish && git push origin master && git push --tags
```

**Comment by barrysteyn** [comment]
@tellnes Yup, that's quite cool. I also use a combination of commands "knitted together" by &&, but the very fact that of using && always makes me think that maybe this should just be scripted :)

Thanks though, I hope you are enjoying using scrypt.

**Comment by barrysteyn** [comment]
@mike-marcacci Would you mind if I closed this issue? If you have time, I would absolutely love the tags (I may even get time to do it myself, but not for the next couple of weeks). What do you say?

**Comment by tracker1** [comment]
@barrysteyn  The command knitting works in *nix and windows environments... bash scripts, not so much.  ;-)  I tend to favor either node JS scripts, or knitted commands for my package.json/scripts

**Comment by mike-marcacci** [comment]
Ah yes, sorry for the slow reply (was out of town) – unfortunately, it's impossible to PR a tag. However, I've got the git hashes for all the 4.x versions (from the npmjs registry). Unfortunately, it's missing the refs for any other versions. You should be able to `git checkout [HASH] && git tag v4.0.[X]` (replacing [HASH] and [X]). Then just `git push origin --tags`.

```json
{
	"4.0.0": "0504f8033e365c6626fc94a6042c6e54b40cbc74",
	"4.0.1": "0e4bdac9e29ab74bb7d21b6a5f0feada96262883",
	"4.0.2": "5115bffcd9eee63f89bc97b35529895f7a6b72bc",
	"4.0.3": "a71081d39e79dfb37b6b02c22b6e69136b0ab245",
	"4.0.4": "9597c3d68e2cc5e35f905c49201b0cd2d6b1ce7f",
	"4.0.5": "3332f85c9fee5f11d352e83102a538b139d2a715",
	"4.0.6": "d8811dadc18ed568dab2129adb1b4d21061ab87c",
	"4.0.7": "29dabe135c2423f3a173aebc6d7e2deaf8d145db"
}
```

Thanks again!

Cheers,
Mike
