### ISSUE TITLE
Better readme table of contents

### ISSUE THREAD

**Issue by fresheneesz** [barrysteyn/node-scrypt#65]
The readme is a little hard to navigate. It has a small table of contents, but I suggest you put in one that's has more sections (deeper sections). If you don't already use a tool for this, I suggest you guys use [doctoc](https://github.com/thlorenz/doctoc) to make one automatically. 

As an aside, it would also be helpful if all the information for a particular method were all in one place, instead of splitting up the documentation into three different areas (API, Examples, and the untitled area between Installation and API). Its pretty confusing to have to switch between them to figure out how to use a function.

**Comment by barrysteyn** [comment]
Hi @fresheneesz 

Please be my guest and open a PR :)

**Comment by barrysteyn** [comment]
Okay, I see you have submitted a PR. Let me look over it...

**Comment by barrysteyn** [comment]
Resolved in #65
