### ISSUE TITLE
scrypt.verify and scyrpt.hash aren't functions

### ISSUE THREAD

**Issue by fresheneesz** [barrysteyn/node-scrypt#68]
While callable, `scrypt.verify` and `scrypt.hash` aren't javascript functions, and don't have `apply`  and `call` methods. Can this be improved?

**Comment by barrysteyn** [comment]
This is true. It is a V8 function whereby you treat objects like functions (I assume that internally, the invocation operators () are just overloaded onto the object). I specifically meant for this to happen. JavaScript when it was first designed was done very quickly, and not that well. So different types of invocations will produce different bindings of the `this` variable to an object. To get around this annoyance, you can use `apply` or `call` methods.

In this case, I don't see it as necessary to be able to specify the bindings. Think of these as objects that cannot bind to any user specified object and which also have the () overloaded on them.

**Comment by tellnes** [comment]
If they are function, they should have `apply` and `call` methods. The current behavior does also break `scrypt.verify instanceof Function`.

An easy solution is just to wrap those functions in js-land.

**Comment by barrysteyn** [comment]
But they are not functions! They are objects with the () operator overloaded (so they look like they are being invoked like a function, but they are not).

**Comment by fresheneesz** [comment]
Neccessary - no. But it is surprising that `apply` isn't available on them. I have a method that wraps functions with callbacks and turns them into functions that return a future/promise. It was surprising that using those methods failed.

**Comment by barrysteyn** [comment]
Darn, I can't remember the exact reason why I did this, but I do remember
at the time that it solved a security issue someone posed to me. Until I
can figure it out/remember it, I am going to keep this as is.

**Comment by tellnes** [comment]
The documentation calls them functions. Also, it does not make sens to talk about objects with the () operator overloaded when we are in a javascript world. Maybe you solved a security issue, but I'm pretty sure you could have solved that while keeping the functionality js-ish.

```
exports.verify = function(a,b,c) {
  return binding.verify(a,b,c)
}
exports.verify.config = binding.verify.config
```

If you implement it like that, then always behave the same for the same arguments independent of what `this` is.

Also, I assume the `config` property is going away in the api redesign.
