### ISSUE TITLE
Some Errors are not javascript Error objects

### ISSUE THREAD

**Issue by fresheneesz** [barrysteyn/node-scrypt#69]
If you pass a string when it expects a buffer, it will pass back some awkward error object. For example:

```javascript
scrypt.verify.config.keyEncoding = "buffer" 
scrypt.verify.config.outputEncoding = "buffer"
scrypt.verify("string", new Buffer(givenPassword, 'utf8'))
```

The above code throws the object:

```
{err_code: 2, err_message:'Module addon argument error: hash must be a buffer or string'}
```

What it should throw is a javascript Error object, with a stack trace. Also, the error is confusing - it says the "hash must be a buffer or string" - well I did in fact pass a string. What it should say is "hash exepcts the keyEncoding buffer" since my keyEncoding is 'buffer'.

**Comment by ironwallaby** [comment]
+1

In Node, *all errors should be instances of the Error prototype*. No exceptions. I've had to wrap the `hash` and `verify` functions in order to enforce this. :(

**Comment by barrysteyn** [comment]
These errors are actually the original C errors from Scrypt. Okay, I will make the errors an instance of Error. It can be part of version 5

**Comment by barrysteyn** [comment]
Lets continue the debate in #72
