### ISSUE TITLE
Segmentation Fault if the hash buffer argument is empty for `scrypt.verify`

### ISSUE THREAD

**Issue by fresheneesz** [barrysteyn/node-scrypt#70]
If you (accidentally) pass in an empty buffer to `verify`, the program seg faults.

`scrypt.verify(new Buffer(''), new Buffer('test', 'utf8'))`

**Comment by barrysteyn** [comment]
This is an assert gone wrong. I will fix it - but actually, since we are going to design a new API, I will make sure it works there.

**Comment by barrysteyn** [comment]
Lets continue the debate in #72
