### ISSUE TITLE
`scrypt.verify` throws when password doesn't match instead of returning false

### ISSUE THREAD

**Issue by fresheneesz** [barrysteyn/node-scrypt#71]
The readme says that `script.verify` should return a boolean, but instead of returning false on a failing check, `verify` throws an object with some internal codes and error messages in a very non-javascripty format.

**Comment by ironwallaby** [comment]
+1

I've run into this behavior too, and think it's inconsistent and bizarre.

**Comment by barrysteyn** [comment]
@fresheneesz Are you talking about the async or the sync behaviour?

**Comment by fresheneesz** [comment]
I'm using the asynchronous version.

**Comment by barrysteyn** [comment]
Lets continue the debate in #72
