### ISSUE TITLE
Alter API To Incorporate Changes From #72

### ISSUE THREAD

**Issue by barrysteyn** [barrysteyn/node-scrypt#73]
Refer to the discussion in #72.

The new API will not have a global config setting. Instead, a config object will be used for. All encodings will also be assumed to be of type *buffer*, which can be transcoded into any of the formats used in the past.

## Params
This will stay the same as previously.

## KDF

Currently: 
 > `kdf(key, scrypt_parameters, [outputLength,] [salt,] [callback_function])`, with global object **scrypt.kdf.config**: `{saltEncoding: 'buffer', keyEncoding: 'buffer', outputEncoding: 'buffer', defaultSaltSize: 32, outputLength: 64}`

This task will change it to:
 > `kdf(key, scrypt_parameters [,salt] [,config] [,callback_function])` Config object will default to the following: `{saltEncoding: 'buffer', keyEncoding: 'buffer', outputEncoding: 'buffer', defaultSaltSize: 32, outputLength: 64}`

If salt is not provided, then a random generated salt will be produced based on settings in the config.

## Hash
Currently: 
 > `hash(key, scrypt_parameters, callback_function)`, with global object **scrypt.hash.config**: `{keyEncoding: 'buffer', outputEncoding: 'buffer'}`

 This task will change it to:
 > `hash(key, scrypt_parameters [,config] [,callback_function])`:
    Config object will default to: `{keyEncoding: 'buffer', outputEncoding: 'buffer'}`

## Verify

Currently:
 > `verify(hash, key, callback_function)` with global object **scrypt.verify.config**: `{hashEncoding: 'buffer', keyEncoding: 'buffer'}`

This will change to:

 > `verify(hash, key, [config], [callback])`. Config object will default to `{hashEncoding: 'buffer', keyEncoding: 'buffer'}`

**Comment by ironwallaby** [comment]
:+1:

**Comment by fresheneesz** [comment]
Looks good!

**Comment by tellnes** [comment]
I want to propose a change to the encoding configuration. Are configuring `outputEncoding` really necessary? Why not always return a `Buffer`?

And what will happen if you defines `'buffer'` as `keyEncoding` (which it defaults to) and pass in a string? Should it convert it to a buffer (assuming it is utf-8) or throw a `TypeError`?

**Comment by fresheneesz** [comment]
@tellnes I agree with you, but this has been discussed and making the config optional was the compromise on that front.

**Comment by BrandonZacharie** [comment]
I believe it should throw a `TypeError` since providing the wrong type is a programmer error.
