### ISSUE TITLE
Documentation error for hash format

### ISSUE THREAD

**Issue by dodtsair** [barrysteyn/node-scrypt#76]
Hello,

The current documentation reads:

    bytes 16-47: 32 bits of random salt
    bytes 48-63: A 16 bit checksum
    bytes 64-95: A 32 bit HMAC of bytes 0 to 63 using a key produced by the scrypt key derivation function.

One side says `bytes 16-47`.  The other says `32 bits`.  There are 8 bits in a byte so that means 32 bits is 4 bytes.  However there are 32 bytes represented by bytes 16 - 47.  I think the documentation should say `32 bytes (256 bits) of random salt`.

Same follows for 16 bit checksum and 32 bit HMAC.

**Comment by barrysteyn** [comment]
Documentation is about to rewritten for a new version of the module. But thanks for bringing this to my attention, and apologies for taking so long to respond (I was extremely busy this last month).
