### ISSUE TITLE
V5 branch compile errors

### ISSUE THREAD

**Issue by alex94puchades** [barrysteyn/node-scrypt#79]
```npm install``` fails in Ubuntu with the following output:
>
npm WARN package.json scrypt@5.0.0 No license field.
-
> scrypt@5.0.0 install /home/alex/node-scrypt
> node-gyp rebuild
>
make: Entering directory '/home/alex/node-scrypt/build'
  COPY ../scrypt/scrypt-1.1.6/config.h
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  AR(target) Release/obj.target/scrypt_wrapper.a
  COPY Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc_cpuperf.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/util/memlimit.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_aesctr.o
  AR(target) Release/obj.target/scrypt_lib.a
  COPY Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o
../src/node-boilerplate/scrypt_kdf_async.cc: In member function ‘virtual void ScryptKDFAsyncWorker::HandleOKCallback()’:
../src/node-boilerplate/scrypt_kdf_async.cc:25:21: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Object>’
     PersistentHandle->Get(NanNew<String>("KDFResult"))
                     ^
scrypt.target.mk:106: recipe for target 'Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o' failed
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o] Error 1
make: Leaving directory '/home/alex/node-scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/alex/.nvm/v0.12.6/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.0-22-generic
gyp ERR! command "node" "/home/alex/.nvm/v0.12.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/alex/node-scrypt
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
>
npm ERR! Linux 3.19.0-22-generic
npm ERR! argv "/home/alex/.nvm/v0.12.6/bin/node" "/home/alex/.nvm/v0.12.6/bin/npm" "i"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! scrypt@5.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@5.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.
>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/alex/node-scrypt/npm-debug.log
>

Additional info:
- using nvm (node version v0.12.6)

**Comment by barrysteyn** [comment]
This has got nothing to do with npm license field. Instead, it seems that
persistent handle is not a pointer for you. This is strange, what version
of node are you using?
On Jul 20, 2015 6:38 AM, "Alejandro Caravaca Puchades" <
notifications@github.com> wrote:
>
> npm install fails in Ubuntu with the following output:
>>
>> npm WARN package.json scrypt@5.0.0 No license field.
>>
>> scrypt@5.0.0 install /home/alex/node-scrypt
>> node-gyp rebuild
>>
>> make: Entering directory '/home/alex/node-scrypt/build'
>> COPY ../scrypt/scrypt-1.1.6/config.h
>> SOLINK_MODULE(target) Release/obj.target/copied_files.node
>> COPY Release/copied_files.node
>> CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
>> CC(target)
Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
>> CC(target)
Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
>> CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
>> AR(target) Release/obj.target/scrypt_wrapper.a
>> COPY Release/scrypt_wrapper.a
>> CC(target)
Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
>> CC(target)
Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
>> CC(target)
Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc_cpuperf.o
>> CC(target)
Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/util/memlimit.o
>> CC(target)
Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc.o
>> CC(target)
Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_aesctr.o
>> AR(target) Release/obj.target/scrypt_lib.a
>> COPY Release/scrypt_lib.a
>> CXX(target)
Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
>> CXX(target)
Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
>> CXX(target)
Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_sync.o
>> CXX(target)
Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o
>> ../src/node-boilerplate/scrypt_kdf_async.cc: In member function ‘virtual
void ScryptKDFAsyncWorker::HandleOKCallback()’:
>> ../src/node-boilerplate/scrypt_kdf_async.cc:25:21: error: base operand
of ‘->’ has non-pointer type ‘v8::Persistentv8::Object’
>> PersistentHandle->Get(NanNew("KDFResult"))
>> ^
>> scrypt.target.mk:106: recipe for target
'Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o' failed
>> make: ***
[Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o] Error 1
>> make: Leaving directory '/home/alex/node-scrypt/build'
>> gyp ERR! build error
>> gyp ERR! stack Error: make failed with exit code: 2
>> gyp ERR! stack at ChildProcess.onExit
(/home/alex/.nvm/v0.12.6/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
>> gyp ERR! stack at ChildProcess.emit (events.js:110:17)
>> gyp ERR! stack at Process.ChildProcess._handle.onexit
(child_process.js:1074:12)
>> gyp ERR! System Linux 3.19.0-22-generic
>> gyp ERR! command "node"
"/home/alex/.nvm/v0.12.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
>> gyp ERR! cwd /home/alex/node-scrypt
>> gyp ERR! node -v v0.12.6
>> gyp ERR! node-gyp -v v2.0.1
>> gyp ERR! not ok
>>
>> npm ERR! Linux 3.19.0-22-generic
>> npm ERR! argv "/home/alex/.nvm/v0.12.6/bin/node"
"/home/alex/.nvm/v0.12.6/bin/npm" "i"

**Comment by tellnes** [comment]
I've got similar errors:

```
> scrypt@5.0.0 install /Users/christian/code/node-scrypt
> node-gyp rebuild

  COPY ../scrypt/scrypt-1.1.6/config.h
  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc_cpuperf.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/util/memlimit.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_aesctr.o
  LIBTOOL-STATIC Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o
../src/node-boilerplate/scrypt_kdf_async.cc:25:21: error: member reference type 'v8::Persistent<v8::Object>' is not a pointer; maybe you meant to use '.'?
    PersistentHandle->Get(NanNew<String>("KDFResult"))
    ~~~~~~~~~~~~~~~~^~
                    .
../src/node-boilerplate/scrypt_kdf_async.cc:25:23: error: no member named 'Get' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    PersistentHandle->Get(NanNew<String>("KDFResult"))
    ~~~~~~~~~~~~~~~~  ^
2 errors generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/christian/code/node-scrypt
gyp ERR! node -v v2.3.3
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i"
npm ERR! node v2.3.3
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! scrypt@5.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@5.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/christian/code/node-scrypt/npm-debug.log
```

I'm on io.js v2.3.3. @alex94puchades is using v0.12.6 according to npm's error output.

I know there has been some changes to v8::Persistent lately.

**Comment by barrysteyn** [comment]
Hi

Okay, I found the problem, and it has been corrected. I have just pushed an update to v5 branch, please can you guys get that and compile with that. Thanks for spotting this, I owe you guys.
