### ISSUE TITLE
passwordHash(key, opt, cb) not working on jailkit

### ISSUE THREAD

**Issue by Martin-Luther** [barrysteyn/node-scrypt#80]
Hello, I'm using scrypt on a node.js project deployed on Debian Jessie, and if `verifyHash(...)` works perfectly, the hashing method `passwordHash` does not work at all.

Debian Jessie
Node 0.12.7

**Comment by barrysteyn** [comment]
Hi Martin

Two questions:

 1. What version of Scrypt are you using?
 2. Can you please expand upon what you mean that passwordHash does not work at all.

Also, note that I am about to release the next version of Node-Scrypt, version 5.0. It is a major rewrite and its not backward compatible. But it addresses all the problems and complaints that have come up with version 4.x

**Comment by Martin-Luther** [comment]
version 4.0.7 on Jessie
I am using  the same version on mac os x ... and the funny thing is that it works like a charm on mac ... 
When are you releasing it (5.0) ?

**Comment by barrysteyn** [comment]
Martin, please can you describe to me what you mean by it not working... Can you give me a screen dump and an example. Version 5.0's is in alpha right now. I will release it in about three weeks. But I don't think using version 5.0 will solve your problem. Again, I need more info if you want me to help you...

**Comment by barrysteyn** [comment]
I am going to close this issue for now. @Martin-Luther please provide more info and I will reopen it.

**Comment by Martin-Luther** [comment]
There is no error message, when passwordHash is called the task is never complete ... it goes to the void ...

``` javascript

scrypt.passwordHash(key, maxtime, function(err, pwdhash) {
    console.debug('never came here !! '+err+' '+ pwdhash );
    if (err) {
        var e = {
            flash: { password: ['Password hashing encountered some troubles. Please, contact your administrator']},
            stack: (err.stack|err.message)
        };
        cb(e)
    } else {
        // cb to process with storing
        cb(false, password)
    }
})
```
I just get an unCaughtException .... and framework is designed to exit on fatal & un handled exceptions .... so the process is terminated in the and ... I usually get a specific message ... but here, none .. nada .. rien du tout ... 

![screen shot 2015-07-25 at 7 42 16 pm](https://cloud.githubusercontent.com/assets/2272470/8890552/74effebe-3305-11e5-9798-84f04034789f.png)

**Comment by barrysteyn** [comment]
Okay, there are a few things that could be wrong. I would need to know some specs of the machine, and also I would need to know what framework you are using. But let me guess: Does your Mac has better specs (more memory, better processor) than your Debian machine? I say this because my first guess is that the hash is created using Scrypt parameters that are too high for the machine. This means that it will take too long to generate it and it will timeout. Can you determine the timeout? Also, can you look at the server log, specifically the syslog.

The problem of you not getting an error message is a typical problem of async callbacks. It will be fixed in version 5.0 but only if you use a promise. But for now, can you try answer the questions I posed above?

**Comment by Martin-Luther** [comment]
the app runs fine on a Macbook Air Late 2010 with 4GB RAM, and a Core2Duo ...
The linux is a Virtual Machine (cloud EC2 like) with 2 cores and 4GB RAM.
What script parameter should I use to eliminate or confirm your guessing ?
It is my own framework, built on top of express.... but it does not matter because I am only requiring Scrypt to perform the hashing... no other dependencies ...

**Comment by barrysteyn** [comment]
Reduce the maxtime. I don't know what you have set it to, but for testing purposes, set it extremely low (much lower than what you have now). I think that would work and would then prove my guess. Your Linux VM on EC2 also adds to my belief - they are very well known for being throttled.

Try it and report back to me.

**Comment by Martin-Luther** [comment]
maxtime is `0.1` ...

**Comment by barrysteyn** [comment]
Okay, so make sure you are creating parameters (run scrypt.params) on the server, and set maxtime to 0.01, maxmem as 0 (it will default to 1 meg) and maxmemfrac as 0.1

**Comment by Martin-Luther** [comment]
The same code run on my mac and on some windows remember :) ?

OK !! Nothing changed with the new settings ... I still get the same behavior ...

**Comment by barrysteyn** [comment]
Then you must run the unit tests on  the server. SSH into your server, find the scrypt module (in node_modules), go to its folder and type `npm run test`

If there is something truly wrong, the tests will fail.

**Comment by barrysteyn** [comment]
@Martin-Luther Please can you run the unit tests and tell me the result

**Comment by Martin-Luther** [comment]
OK !!! I've got news ... good for you... bad for me ...
What I forgot to mention is that i'm running the app under a chrooted env (jailkit) ...
When I re install Scrypt using `root`, and start the app with the root user, it works fine .. like good old times !
When I switch back to the jailed user, for some reason that I don't really understand, passwordHash does not work... while verifyHash has no problem being called and executed with success... 

Here is a partial the output i got while running `npm run test` as root :

``` tty
ok 42 - Password Hash (Asynchronous): hash key with correct arguments: key string and scrypt parameters object # time=43.192ms

    # Subtest: Password Hash (Asynchronous): hash key with correct arguments: key string and maxtime number
    ok 1 - Asynchronous test: err object is correctly set as null
    ok 2 - The key was hashed successfully, as expected
    ok 3 - The hash that was returned is of type 'string', as expected (because it is base64 encoded)
    1..3
ok 43 - Password Hash (Asynchronous): hash key with correct arguments: key string and maxtime number # time=534.813ms

    # Subtest: Password Hash (Aynchronous): hash key with correct arguments: key string, maxtime number and maxmem number
    ok 1 - Asynchronous test: err object is correctly set as null
    ok 2 - The key was hashed successfully, as expected
    ok 3 - The hash that was returned is of type 'string', as expected (because it is base64 encoded)
    1..3
ok 44 - Password Hash (Aynchronous): hash key with correct arguments: key string, maxtime number and maxmem number # time=565.898ms

    # Subtest: Password Hash (Asynchronous): hash key with correct arguments: key string,maxtime number, maxmemnumber and maxmem_frac number
    ok 1 - Asynchronous test: err object is correctly set as null
    ok 2 - The key was hashed successfully, as expected
    ok 3 - The hash that was returned is of type 'string', as expected (because it is base64 encoded)
    1..3
ok 45 - Password Hash (Asynchronous): hash key with correct arguments: key string,maxtime number, maxmemnumber and maxmem_frac number # time=562.648ms

    # Subtest: Password Hash (Asynchronous): hash key with correct arguments: key string object and scrypt parameters object
    ok 1 - Asynchronous test: err object is correctly set as null
    ok 2 - The key was hashed successfully with a string object, as expected
    ok 3 - The hash that was returned is of type 'string', as expected (because it is base64 encoded)
    1..3
ok 46 - Password Hash (Asynchronous): hash key with correct arguments: key string object and scrypt parameters object # time=5.204ms

    # Subtest: Password Hash (Asynchronous): hash key with correct arguments: key buffer and scrypt parameters object
    ok 1 - Asynchronous test: err object is correctly set as null
    ok 2 - The key was hashed successfully with a buffer, as expected
    ok 3 - The hash that was returned is of type 'string', as expected (because it is base64 encoded)
    1..3
ok 47 - Password Hash (Asynchronous): hash key with correct arguments: key buffer and scrypt parameters object # time=4.856ms

    # Subtest: Password Verify: incorrect arguments - no arguments present
    ok 1 - An error was correctly thrown because at one least two arguments are needed - in this case, no arguments were given
    ok 2 - The correct object is returned, namely: {"err_code":2,"err_message":"Module addon argument error: both hash and key are needed"}
    1..2
```
Yeah ...seems okay huh !
And with the jail user it won't work because of a python issue that I need to solve before running  `node-gyp` properly... 

Then you are going to ask me how did I install Scrypt in the first place ? 
I installed Scrypt outside the jail, then copied the module to `/opt/node/share` before doing a `jk_cp -j /to/myjail`
This trick worked for me with 2 other node_modules that I could not compile via `npm install`. You don't usually give access for gcc/g++ or make to a jailed user ... 

The only problem that I can think of with this maneuver is when you have static path references ... the root and the jailed user don't see path the same way: the '/' is not located at the same place for everyone ... I have the same problem with my framework: it would create a file containing constants of important path to make thing easier when you need a dir location later for example... I won't go into details but: is it possible that you too need to make somehow static references: like writing once a file with locations that you access later when the code is running ? This would make sens to me ...

Thank you for your time.

**Comment by barrysteyn** [comment]
I am closing this issue because it is a problem with setup, not with an inherent bug in the code. Please shout out to me over here and I will try help you as best as I can.

Node-gyp is just a build definition, identical to make but it is supposed to be much easier. It uses python to set things up. What it actually does is take input and spit out a makefile. Why do we need this for node-scrypt? Because it is a C/C++ addon and what I am doing is compiling scrypt with v8 bindings so it is accessible to node. Both verifyPassword and passwordHash all call the same underlying work function whereby the scrypt hash function is calculated. If it works for verify, it must work for hash.

I think there is something more fundamentally wrong, but you are in the dark because you cannot get at the exception. Version 5.0 will help if you use a promise (it will always catch the exception). As for now, check the log files and report back to me.

**Comment by Martin-Luther** [comment]
My workaround worked for 2 other modules using C/C++  ... :(
But you are right, I have to get rid of the python error I get first.
Thanks again.

**Comment by barrysteyn** [comment]
Those two other modules are perhaps not C/C++ addons. Perhaps they are pure node/iojs modules (don't use any C/C++).

Scrypt does link to Node's openssl library. If you are jailing something, then this would be the first suspect. But then verify would definitely not work (just like hash, it uses openssl heavily). So that cannot be the problem.

That leaves just one problem: It is the parameter function. Actually, I am sure of this. You see, it is quite a CPU intensive process (just a short burst though) to translate human read able aspects (maxtime etc) into the parameter object. The passwordHash can actually take the parameter directly, so why don't you try just using it directly. Here, try this:

    scrypt.passwordHash(key, {N:1, r:1, p:1}, function(err, pwdhash) {...})

I would almost put money on it that the above would work for you. Try it and tell me.

**Comment by Martin-Luther** [comment]
It worked using root previously ... it is not CPU related ... But I'll try and get back to you in 5.

**Comment by Martin-Luther** [comment]
OK ! Now you have to explain why the fuck this worked ! I'm lost here. 
Knowing that when I changed the user, without doing anything, everything work fine `jailed -> root`...
Now back with my jailed user, and "my workaround" PLUS the fact that I applied your recommandation to put `{N:1, r:1, p:1}` instead of the `0.1`maxtime value, it is working ...
I don't think it is CPU related since it worked with root just before hundreds of times.

**Comment by barrysteyn** [comment]
I agree it has nothing to do with CPU, I was just mentioning that as an aside. The parameter function is actually a translation function: It translates maxtime, maxmem and maxmemfrac (all supposedly human understandable) into the scrypt parameter object {N:?,r:?,p:?} (the question marks indicate and value).

To determine those values, it uses various shared libraries. Check out the `memtouse` and `scryptenc_cpuperf` functions.  Those are the functions that are causing your problem. I suspect that the type of access they need to do their computations is too restrictive in a jail (although I am by no means an expert in jails).

Here is a way you can get round it: It is only a translation function, so if as a root user you run the params function with your desired maxtime, maxmem and maxmemfrac inputs, you will get a scrypt params object of it. You can then use that params object directly in your jail.

**Comment by Martin-Luther** [comment]
Thanks for your help (sincerely), I will look into it: it makes sense. It would be really nice if you did not need those shared libraries :( 
The less dependencies you have the more easy it get to integrate/use Node Scrypt.

**Comment by barrysteyn** [comment]
Well, actually, that translation function is not really part of Scrypt, as
you saw yourself, it works fine if you just pass it a scrypt params object.
It is there to make life easier. I don't think there is any other way to
make such functionality without referring to external libraries.
