### ISSUE TITLE
node-gyp rebuild error on linux EC2-instance

### ISSUE THREAD

**Issue by yossazou** [barrysteyn/node-scrypt#87]
Hi everybody,

I'm trying to install node-scrypt on linux EC2-instance but I'm getting a lot of errors. I hope someone can help me fix them.

Thank you !!

compilation terminated.
make: *** [Release/obj.target/scrypt/scrypt_node.o] Error 1
make: Leaving directory `/home/ec2-user/direct_v_1/node_modules/scrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.14.48-33.39.amzn1.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/direct_v_1/node_modules/scrypt
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN EPACKAGEJSON direct@0.0.1 No description
npm WARN EPACKAGEJSON direct@0.0.1 No repository field.
npm WARN EPACKAGEJSON direct@0.0.1 No license field.
npm ERR! Linux 3.14.48-33.39.amzn1.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "scrypt" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.1
npm ERR! code ELIFECYCLE

npm ERR! scrypt@4.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@4.0.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/direct_v_1/npm-debug.log

**Comment by barrysteyn** [comment]
Hi. Scrypt version 5 is being released sometime today. Use that version, it will work then.
