### ISSUE TITLE
npm install node-scrypt causes error

### ISSUE THREAD

**Issue by ngoctranfire** [barrysteyn/node-scrypt#88]
Even with the node-gyp install globally, this is still causing me to get some issues. Please take a look at this!
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-scrypt" "--save"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-scrypt@0.0.1 preinstall: `node-waf clean || true; node-waf configure build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-scrypt@0.0.1 preinstall script 'node-waf clean || true; node-waf configure build'.
npm ERR! This is most likely a problem with the node-scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || true; node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ntran/Desktop/conscious-life/npm-debug.log

**Comment by Michal--M** [comment]
Maybe not related, but on Win7 with MSVS 2015 I am getting this one:

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\iojs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\iojs\\node.exe" "C:\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\GitHub\node_modules\scrypt
gyp ERR! node -v v2.5.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\iojs\\node.exe" "C:\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "scrypt"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! code ELIFECYCLE

Caused by this compilation error:

C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\time.h(39): error C2011: 'timespec': 'struct' type redefinition (compiling source file ..\scrypt\scrypt-1.1.6\lib\scryptenc\scryptenc_cpuperf.c) [d:\GitHub\node_modules\scrypt\build\scrypt_lib.vcxproj]

Found somewhere that adding HAVE_STRUCT_TIMESPEC to <PreprocessorDefinitions> in the project file might help(?)

**Comment by barrysteyn** [comment]
@ngoctranfire I need more information. Unfortunately, it builds fine for me on Mac (and I used identical version of node and node-gyp to do this). As the error says, please include `npm install -g node-gyp`

**Comment by barrysteyn** [comment]
@Michal--M - Windows is always going to be a pain. Do me a favour, can you alter the config file to define HAVE_STRUCT_TIMESPEC and see if it compiles.

**Comment by ngoctranfire** [comment]
@barrysteyn ,
I don't know exactly what happened, but I just did it again and everything worked! Sorry for the issue >.>

**Comment by Demurgos** [comment]
Hi,
I currently have the same issue using VS2015. I'm just starting to learn C++ so I don't understand very well where to edit this config file. If I succeed in building it I'll let you know.

````
  Copying scrypt/win/include/config.h to scrypt/scrypt-1.1.6/config.h
          1 fichier(s) copié(s).
  win_delay_load_hook.c
  Generating code
  Finished generating code
  copied_files.vcxproj -> K:\web\node-scrypt\build\Release\\copied_files.node
  salt.c
  keyderivation.c
  pickparams.c
  hash.c
  win_delay_load_hook.c
  scrypt_wrapper.vcxproj -> K:\web\node-scrypt\build\Release\\scrypt_wrapper.li
  b
  sha256.c
  crypto_scrypt-sse.c
  scryptenc_cpuperf.c
  memlimit.c
  mman.c
  gettimeofday.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\time.h(39): er
ror C2011: 'timespec': 'struct' type redefinition (compiling source file ..\scr
ypt\scrypt-1.1.6\lib\scryptenc\scryptenc_cpuperf.c) [K:\web\node-scrypt\build\s
crypt_lib.vcxproj]
  K:\web\node-scrypt\scrypt\win\include\gettimeofday.h(9): note: see declaratio
  n of 'timespec' (compiling source file ..\scrypt\scrypt-1.1.6\lib\scryptenc\s
  cryptenc_cpuperf.c)
  win_delay_load_hook.c
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd K:\web\node-scrypt
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! scrypt@5.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@5.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     K:\web\node-scrypt\npm-debug.log
````

**Comment by Michal--M** [comment]
Since I had not been able to include the directive HAVE_STRUCT_TIMESPEC in the project file, I performed the following nasty workaround: located the file %appdata%/npm-cache/scrypt/4.0.7/package.tgz/package.tar/package/scrypt/win/include/gettimeofday.h and deleted the timespec struct there.

**Comment by barrysteyn** [comment]
You guys are now finding out my problems with Windows: This is inherently a library designed for posix systems. I am slowly working to make this library more compatible on windows. In my next major release, I will make it rock solid. In the mean time, we unfortunately need these types of work arounds.

**Comment by Michal--M** [comment]
Honestly [node-gyp page](https://github.com/nodejs/node-gyp) clearly says that we should use MSVS 2013, not 2015. So it may in fact work just fine :)

**Comment by barrysteyn** [comment]
@Michal--M Please can you clone and build branch V5.3 - I think I may have fixed your problem with the help of @Demurgos. Please tell me if it is working now.

**Comment by Michal--M** [comment]
Confirming that 5.2.0 builds fine with MSVS 2015 (just two minor warnings)
```
..\src\node-boilerplate\scrypt_hash_sync.cc(32): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
... scrypt\src\node-boilerplate\inc\scrypt_hash_async.h(43): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data (compiling source file ..\src\node-boilerplate\scrypt_hash_async.cc)

```

**Comment by barrysteyn** [comment]
Yeah, those warnings are not really a problem because I don't expect it to be anything more than a 32 bit integer. Still, I will get round to fixing them some day, but it won't affect the security in anyway.

**Comment by sunqihang** [comment]
Hi @barrysteyn, when I try to npm install -g scrypt, I am getting the error 
 npm install -g scrypt

> scrypt@6.0.3 preinstall C:\Users\a548533\AppData\Roaming\npm\node_modules\.staging\scrypt-2e21350b
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install C:\Users\a548533\AppData\Roaming\npm\node_modules\scrypt
> node-gyp rebuild


C:\Users\a548533\AppData\Roaming\npm\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\a548533\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\a548533\AppData\Roaming\npm\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying scrypt/win/include/config.h to scrypt/scrypt-1.2.0/config.h
  The system cannot find the file specified.
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  copied_files.vcxproj -> C:\Users\a548533\AppData\Roaming\npm\node_modules\scrypt\build\Release\\copied_files.node
  memlimit.c
  keyderivation.c
  pickparams.c
  hash.c
  win_delay_load_hook.cc
  scrypt_wrapper.vcxproj -> C:\Users\a548533\AppData\Roaming\npm\node_modules\scrypt\build\Release\\scrypt_wrapper.lib
  crypto_scrypt.c
  crypto_scrypt_smix.c
  warnp.c
  sha256.c
  insecure_memzero.c
..\scrypt\scrypt-1.2.0\lib\crypto\crypto_scrypt.c(172): error C2059: syntax error : '.' [C:\Users\a548533\AppData\Roaming\npm\node_modules\scrypt\build\scrypt_lib.vcxproj]
..\scrypt\scrypt-1.2.0\lib\crypto\crypto_scrypt.c(187): error C2059: syntax error : '}' [C:\Users\a548533\AppData\Roaming\npm\node_modules\scrypt\build\scrypt_lib.vcxproj]
  scryptenc_cpuperf.c
  mman.c
  gettimeofday.c
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\a548533\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\a548533\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\a548533\AppData\Roaming\npm\node_modules\scrypt
gyp ERR! node -v v7.7.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\a548533\AppData\Roaming\npm\node_modules\scrypt\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\a548533\AppData\Roaming\npm\node_modules\scrypt\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\a548533\\AppData\\Roaming\\npm\\node_modules\\scrypt\\node_modules' }
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\a548533\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "scrypt"
npm ERR! node v7.7.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\a548533\AppData\Roaming\npm-cache\_logs\2017-03-03T19_29_41_850Z-debug.log


It has bugging me for more than 1 week.

Please give some suggestions

Thanks
