### ISSUE TITLE
Migrating from v4 to v5

### ISSUE THREAD

**Issue by nimish** [barrysteyn/node-scrypt#91]
Hi, trying to migrate from scrypt < 5 to 5. The previous code just uses the ancient passwordHash and friends. 

What's the migration path? Are the parameters compatible? What are the new equivalents of passwordHash and verifyHash?

**Comment by barrysteyn** [comment]
Read the documentation :)

**Comment by nimish** [comment]
Hi, I have read the documentation (Readme.md) and there's nothing in there about migrating from passwordHash to kdf while maintaining compatibility with existing output data. 

For future reference, here's what works:

1) `verifyHash` and `verifyKdf` work identically since the struct generated by node-scrypt has all of the required parameters (N, p, r), as long as you parse the base64 output into a `Buffer`
2) `kdf` is the new `passwordHash` and instead of passing `maxtime` directly you should generate (N, p, r) via `scrypt.params[Sync]`; you should then convert the resultant `Buffer` into a base64 encoded string


Was that so hard?

**Comment by barrysteyn** [comment]
I maintain this module on a voluntary basis as I have a full time job.
Answering requests like yours take time, but if you RTFM, you get the
answer (as you have just proven). Instead of making snide comments like
"Was that so hard", why don't you make a pull request with some additions
to the documentation.

**Comment by nimish** [comment]
Hey man, you tell me to RTFM, and it's not in the manual! 

I had to reverse engineer this based on comparing the parameters generated and using previous versions.  

It's up to you to include this if you want. Someone google-ing for it will find it here. I personally don't think it's worth it since the particular functions were already deprecated in v4.

**Comment by BrandonZacharie** [comment]
See section ["Migrating To Version 5"](https://github.com/barrysteyn/node-scrypt/blob/master/Readme.md#migrating-to-version-5) ([added 27 days ago](https://github.com/barrysteyn/node-scrypt/commit/c89c36e1f85675b1467e0b8cab13a316efd36334))

**Comment by nimish** [comment]
That doesn't cover passwordHash and verifyHash. Anyway, it's now documented here.
