### ISSUE TITLE
Converting Old Passwords

### ISSUE THREAD

**Issue by austint** [barrysteyn/node-scrypt#94]
Will updating to the latest version make old password hashes – stored on a database, let's say – unusable, i.e. would users need to generate new password kdfs with the newest version of Scrypt?

Trying to see if I can upgrade to the latest without losing the stored passwords.

Thanks!

**Comment by barrysteyn** [comment]
Hi @austint 

The answer to your question: Of course the stored password hashes are still valid. I have not changed the internal format for the hashes, I have just upgraded the module and made major changes to the module itself. So you can still use your old password hashes :)

**Comment by austint** [comment]
Badass! Thanks for the extremely quick response :D
