### ISSUE TITLE
unsafe use of arguments

### ISSUE THREAD

**Issue by AVVS** [barrysteyn/node-scrypt#95]
1. https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments

instead of passing reference of `arguments` to another function, we must make a copy before that.
Quote from there:

```js
// Workaround for proxying is to create array in-line:

function doesntLeakArguments() {
                    //.length is just an integer, this doesn't leak
                    //the arguments object itself
    var args = new Array(arguments.length);
    for(var i = 0; i < args.length; ++i) {
                //i is always valid index in the arguments object
        args[i] = arguments[i];
    }
    return args;
}
It takes a lot of code and is annoying so it might be worth to analyze if it's really worth it. Then again optimizing always takes a lot of code when more code means more explicitly nailed down semantics.
```

**Comment by AVVS** [comment]
every function that uses `checkNumberOfArguments` and `checkAsyncArguments` is affected.

**Comment by barrysteyn** [comment]
Can you explain why this is needed please. I looked at the link you pointed to, but it does not explain what is wrong with referring to arguments.

**Comment by AVVS** [comment]
code becomes unoptimizable, and reference is leaked between functions, basically v8 internals work in a way that you can not ever pass arguments anywhere else except for `func.apply(context, arguments)`. Probably if you want any more info than that you might want to lookup a few talks from nodeconfeu 2013/4 and/or ask author of bluebird for more insight - I'm limited in my knowledge on the guts of the v8 here

**Comment by barrysteyn** [comment]
Please can you point me to those talks. I would love to view them. I still don't really know why this is needed.

**Comment by AVVS** [comment]
http://stackoverflow.com/questions/23509312/does-node-js-really-not-optimize-calls-to-slice-callarguments

This should explain it. Example is different to the problem in this code, but problem is the same

**Comment by barrysteyn** [comment]
Hi @AVVS 

Thank you for pointing me to this documentation. It really is useful (and interesting). All in all, I am still not an expert in this subject, but the stackoverflow article you gave convinced me enough that it wouldn't really hurt.

The only problem is the code bloat. For this to work properly, one cannot add a method to extract the arguments in a prototype object. No, the only way it will work is to actually put this code in all functions (where is a macro when you need one).

So I have things I would appreciate if you could look into:

 1. Will this work: `var args = Array.prototype.slice.call(arguments)`. It's very short, so if we did go down this route, it would have to be a one liner like this.
 2. How much of a problem is this really? The examples given were very simple (adding some double numbers together). These functions are really plugins into a very specialized library that is designed to take a long time to complete. Making the calling functions more efficient will probably not achieve anything.
 3. The stackoverflow article mentions that the makers of node know about this problem. This is the link provided: https://github.com/nodejs/node-v0.x-archive/commit/91f1b250ecb4fb8151cd17423dd4460652d0ce97 - Now, this over four years old. What with Node moving so quickly, has this been fixed up yet? It very well may have.

I will wait for your comments.

**Comment by AVVS** [comment]
1. It won't work, it leaks arguments by initializing the object and makes func non-optimizable, therefore killing the performance of this function (you don't really care unless you have thousands of users generating password, but if you do - this actually hurts you)

2. Yes, it's designed that way, but we don't want to block the loop for more than needed and we want to pass the control to an underlaying async IO operation and continue serving requests

3. this is more or less the issue with the `arguments` itself and there is no real way to avoid it - compiler can't predict how the function would work when arguments is used and so far it's just the same of the issue as before.

You can make a "macro", ie INLINE_SLICE(args) and expand it during pre-publish / build step if code bloat is to be avoided, but I don't think it would really hurt.

**Comment by tellnes** [comment]
This should be easy solvable by just doing:

```
function(a, b, c, d, e) {
  checkNumberOfArguments(a, b, c, d, e)
}
```

**Comment by barrysteyn** [comment]
@tellnes, I suppose that would work, but it wouldn't be very [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

**Comment by barrysteyn** [comment]
@AVVS I will come up with a solution over the weekend (or if I have some time, maybe even today). When I do have a solution, can I please ask you to look at it?

**Comment by AVVS** [comment]
@barrysteyn absolutely

**Comment by mietek** [comment]
Why are you trying to optimise a wrapper around a key derivation function that was explicitly [designed to be slow](http://www.tarsnap.com/scrypt.html)?

**Comment by barrysteyn** [comment]
Lets assume I don't optimize, then someone can make another library that
does optimize. Now people who use the optimized library have an advantage
over people who use the unoptimized library. The fact is that the core of
the function is slow, but everything else should be efficient.


Barry Steyn Blog <http://doctrina.org> LinkedIn
<http://ca.linkedin.com/in/barrysteyn> GitHub
<https://github.com/barrysteyn>

**Comment by barrysteyn** [comment]
I am going to close this for now. If you feel very passionate about this, please send a patch.
