### ISSUE TITLE
Buffers to Strings and Strings to Buffers

### ISSUE THREAD

**Issue by austint** [barrysteyn/node-scrypt#99]
Hey man!

So, we are using your packages in our app, which also uses Mongo, and we are running into some issues. I tried figuring it out from your docs, but not luck so far. Maybe you could shed some light on our problem.

I'm using the following to generate a new scrypt kdf:

```javascript
scrypt.kdf('password', { N: 1, r:1, p:1 }, function (err, newKdf) {
// send kdf to Mongo as a property on a passwordObject
});
```

The result of this method is a buffer, which – when sent to Mongo – gets stored as a BSON Object that looks like this:

```javascript
scryptPassword: 
   { _bsontype: 'Binary',
     sub_type: 0,
     position: 96,
     buffer: <Buffer 73 63 72 79 70 74 00 01 00 00 00 01 00 00 00 01 37 93 31 18 52 57 a6 cc ff 74 b2 5d 7e 1d fd f4 d5 9b 1c 73 f3 20 52 0c f3 7a 0a 1f 9e 7a 99 59 f3 24 ... > } }
```

When attempting to use `scrypt.verifyKdf`, I'm trying to convert `scryptpassword.buffer` back to a String, but all of the encoding types I've tried – e.g. utf-8, hex, etc. – produce the following error when passed to the scrypt.verifyKdf method:

`Error: data is not a valid scrypt-encrypted block`

This is even the case when I go from a scrypt-generated Buffer --> String --> Buffer.

We need to store the scrypt-generated hash as a String in Mongo, and not a BSON Object, for legacy purposes. It seems like something is getting lost in translation. Any help you could offer would be very, very much appreciated.

Thank you!

Best,
Austin

**Comment by austint** [comment]
Seems like base64 encoding is working. Maybe add this to the docs in a more obvious spot? Thanks dude! :D

**Comment by barrysteyn** [comment]
I don't understand your request. Do you mean that maybe I should add in the documentation that the default encoding for binary strings is Base64?

**Comment by austint** [comment]
Oh, no problem. Yeah, exactly that!

I was thinking it could be useful since kdf returns a buffer, and you can't tell that it has [A-Z, a-z, 0-9, and + /, which would indicate that it is Base64.

I saw that you converted a Buffer to a String using Base64 in one of the examples deeper in the docs, but it could save some people time – particular programmers who aren't as well versed in the different types of encodings – if it was stated explicitly.

Thanks again!

**Comment by KrisSiegel** [comment]
This is the same issue we ran into with upgrading. Previously we'd generate the hash and store in a database as a string. When we upgraded now everything is a buffer so we needed to convert that to a string and then be able to bring the string back in from the database to let it compare. Version 4 was far easier to use. Oddly enough every time I call kdfSync() I get a different result with the same exact input which leads me to believe I'm doing something wrong.

So
```javascript
var password = "password";

console.log(scrypt.kdfSync(password, scrypt.paramsSync(0.1)).toString("base64"));
console.log(scrypt.kdfSync(password, scrypt.paramsSync(0.1)).toString("base64"));
console.log(scrypt.kdfSync(password, scrypt.paramsSync(0.1)).toString("base64"));
console.log(scrypt.kdfSync(password, scrypt.paramsSync(0.1)).toString("base64"));
console.log(scrypt.kdfSync(password, scrypt.paramsSync(0.1)).toString("base64"));
```

All of those return a different string so I feel like I must be doing something wrong here but that's essentially how the previous API worked except it was hash and not kdf.

**Comment by barrysteyn** [comment]
@KrisSiegel: It is a buffer, so you can transcode it to any string type you want. Choose Base64 (I will document better very soon) As to getting a different string output every time you run the function, if you did not get a different string, then this module would be incredibly insecure. Please read the FAQ section, all the answers are there. And don't worry, it is by design that the output changes all the time (hint: random salt).

**Comment by barrysteyn** [comment]
@austint 

Now that I have read your issue again, I realize that this is not a fault with any documentation per se. I never encode anything in the buffer, so things should work, whatever encoding you choose.

However, if you look at the snippet you sent me, I see that mongo is storing it as a binary. Unless you transcode in base64, you will not get the correct string out of it (read https://en.wikipedia.org/wiki/Binary-to-text_encoding to understand why).

**Comment by KrisSiegel** [comment]
@barrysteyn yeah you're right I was confused by the different behavior and took it to mean version 4 generated the same result every time which is obviously wrong.

What tripped me up was when attempting to run verifyKdf and passing in the base64 encoded string from the database while comparing it to the current user's input. The solution was taking the string stored from the database and creating a buffer like this:

```javascript
let storedKdf = new Buffer(storedString, "base64");
```

That second parameter was what did it as a new buffer defaults to utf-8 unless specified.

**Comment by barrysteyn** [comment]
Many people have asked for examples like you asked for, but this is
actually the function of a buffer. I don't feel it is the job of this
module to demonstrate things that are part of Node's API.

I am however thinking of starting a wiki where we can all combine our
knowledge about things such as this. What do you think? Would you add your
examples to the wiki?

**Comment by KrisSiegel** [comment]
Sure I understand, using a Buffer is part of the node API and you don't want to have APIs from other, outside components in your documentation. But as a module author, if you wish for the best adoption / experience of your module by others, then I am of the opinion that you can't take the pure "only my APIs" road.

I would argue that the best modules have full end-to-end examples right in their documentation. Providing examples that *technically* work but don't work in the vast majority of use cases your module would be used in just seems silly to me.

But hey it's your module, do what you think is best. I just don't think people visit wikis; I think they look at the README and if it doesn't work they either move to the next module or they start searching issues / code / google to try and figure out what's up. At least that's been my experience working with others.

**Comment by barrysteyn** [comment]
My thinking is opposite. I find that when I adopt a module, I want my README to be as concise and to the point as possible. However, I do get lots of requests. What I may do is add to the examples for how to store a buffer in binary, and then bring it back to the original string.

Regarding people adopting the module, I don't think inadequate documentation will make them use something else. Specially something like a fundamental crypto library such as this module provides. Still, I do want people to have an easy time...

**Comment by austint** [comment]
@barrysteyn that's true. Your call on it, obviously. I figured it out eventually, and maybe this thread will be enough for anyone who runs into the same problem. Thanks again for getting back to me!

**Comment by zhuangya** [comment]
LIFE SAVING THREAD!!!!

**Comment by iamlothian** [comment]
Was hoping this was my answer, but alas i am still searching. Can anyone tell me what's going wrong here?

Lets take make a new account with a password
```javascript
...
var account = new model(data); // my mongo schema model
account.password = (yield scrypt.kdf(data.password, PasswordKDFParams)).toString('base64');
account.save();
...
```
_don't be sacred of the `yield` keyword it works_

here is my mongo record with the password encrypted as a base64 string
```javascript
{ "_id" : ObjectId("564ac38041fab812241297ed"), "username" : "admin", "password" : "c2NyeXB0ABEAAAAIAAAAAYDFAzK/wcsTSGx86THQgTgnpNhsfZLe9g0JJ1iOBCMGZx89MbJTT8QvEwS1E169dn/lUNB48uPPQ75qkHUYfIfj8wOSMfscsid99s+4QYTY", "dateUpdated" : ISODate("2015-11-17T06:04:48.532Z"), "dateCreated" : ISODate("2015-11-17T06:04:48.532Z"), "__v" : 0 }
```

Then later I pull the password has back out 
```javascript
...
var passBuffer = new Buffer(account.password, "base64"),
    verified = yield scrypt.verifyKdf(cleartext, passBuffer);
...
``` 
To which I am greeted:
```
[Error: data is not a valid scrypt-encrypted block]
```

**Comment by zhuangya** [comment]
I think you need to base64decode before you pass the hashed result to
verifyKdf


2015年11月17日星期二，matt <notifications@github.com> 写道：

**Comment by KrisSiegel** [comment]
verifyKdf needs a buffer for your hash and a buffer for your input. Essentially:

```javascript
var hashBuffer = new Buffer(hashFromDatabase, "base64");
var inputBuffer = new Buffer("my password");
console.log(scrypt.verifyKdfSync(hashBuffer, inputBuffer));
```

**Comment by iamlothian** [comment]
Yeah sorry man, every thing here was right. I had the arguments of `verifyPassword` around the wrong way [face palm]. Thanks for the quick response anyway :)

**Comment by wmkamerman** [comment]
This thread is seriously life saving. Spent 2 days figuring this out. Please add a full example in the docs... Thanks for the answers!
